#ifndef __CS5530_DEMO_H
#define __CS5530_DEMO_H


//#include "stdio.h"
//#include "stm32f10x_type.h"
////#include "STM32_SPI.H"
//#include "STM32_PWM.H"
//#include "STM32_ADC.H"
//#include "STM32_USART.H"
//#include "STM32F10x_BitBand.H"
//#include "STM32_SYSTICK.H"

////#include "STM32_SPI.H"






void CS5530Demo_Configuration(void);
void CS5530Demo_Server(void);
void TM1616_Configuration(void);
void CS5530_Configuration(void);
void TM1616_DIS(void);


#endif

