#ifndef __TM1638_TEST_H
#define __TM1638_TEST_H


//#include "stdio.h"
//#include "stm32f10x_type.h"
////#include "STM32_SPI.H"
//#include "STM32_PWM.H"
//#include "STM32_ADC.H"
//#include "STM32_USART.H"
//#include "STM32F10x_BitBand.H"
//#include "STM32_SYSTICK.H"

////#include "STM32_SPI.H"






void TM1638_Configuration(void);
void TM1638_Server(void);
void TM1638_PinSet(void);
void TM1638_DIS(void);


#endif

