SET PATH=D:\Program Files (x86)\MDK\CORE\ARM\ARMCC\Bin;C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma SDK\bin;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Users\RUSH4\AppData\Local\Microsoft\WindowsApps;C:\Users\RUSH4\AppData\Local\GitHubDesktop\bin;D:\Program Files (x86)\MDK\CORE\ARM\Segger;
SET CPU_TYPE=STM32F103RC
SET CPU_VENDOR=STMicroelectronics
SET UV2_TARGET=AMPLCDV11
SET CPU_CLOCK=0x007A1200
"D:\Program Files (x86)\MDK\CORE\ARM\ARMCC\Bin\ArmCC" --Via ".\output\obj\main.__i"
"D:\Program Files (x86)\MDK\CORE\ARM\ARMCC\Bin\ArmCC" --Via ".\output\obj\stm32_it.__i"
"D:\Program Files (x86)\MDK\CORE\ARM\ARMCC\Bin\ArmCC" --Via ".\output\obj\stm32_wow.__i"
"D:\Program Files (x86)\MDK\CORE\ARM\ARMCC\Bin\ArmCC" --Via ".\output\obj\a3987_test.__i"
"D:\Program Files (x86)\MDK\CORE\ARM\ARMCC\Bin\ArmCC" --Via ".\output\obj\adc_temperature.__i"
"D:\Program Files (x86)\MDK\CORE\ARM\ARMCC\Bin\ArmCC" --Via ".\output\obj\adc_test.__i"
"D:\Program Files (x86)\MDK\CORE\ARM\ARMCC\Bin\ArmCC" --Via ".\output\obj\buzzer_test.__i"
"D:\Program Files (x86)\MDK\CORE\ARM\ARMCC\Bin\ArmCC" --Via ".\output\obj\can_test.__i"
"D:\Program Files (x86)\MDK\CORE\ARM\ARMCC\Bin\ArmCC" --Via ".\output\obj\cd4511bm_test.__i"
"D:\Program Files (x86)\MDK\CORE\ARM\ARMCC\Bin\ArmCC" --Via ".\output\obj\dac_test.__i"
"D:\Program Files (x86)\MDK\CORE\ARM\ARMCC\Bin\ArmCC" --Via ".\output\obj\fx2n_14mr.__i"
"D:\Program Files (x86)\MDK\CORE\ARM\ARMCC\Bin\ArmCC" --Via ".\output\obj\iap.__i"
"D:\Program Files (x86)\MDK\CORE\ARM\ARMCC\Bin\ArmCC" --Via ".\output\obj\iccard.__i"
"D:\Program Files (x86)\MDK\CORE\ARM\ARMCC\Bin\ArmCC" --Via ".\output\obj\lk3u_40mr.__i"
"D:\Program Files (x86)\MDK\CORE\ARM\ARMCC\Bin\ArmCC" --Via ".\output\obj\offline_isp.__i"
"D:\Program Files (x86)\MDK\CORE\ARM\ARMCC\Bin\ArmCC" --Via ".\output\obj\oled096_test.__i"
"D:\Program Files (x86)\MDK\CORE\ARM\ARMCC\Bin\ArmCC" --Via ".\output\obj\pwm_led.__i"
"D:\Program Files (x86)\MDK\CORE\ARM\ARMCC\Bin\ArmCC" --Via ".\output\obj\pwm_test.__i"
"D:\Program Files (x86)\MDK\CORE\ARM\ARMCC\Bin\ArmCC" --Via ".\output\obj\pwrtest.__i"
"D:\Program Files (x86)\MDK\CORE\ARM\ARMCC\Bin\ArmCC" --Via ".\output\obj\r2a15908sp.__i"
